sudo: false
language: python
python: 3.6
cache:
  - npm
  - directories:
    - $HOME/results
install:
  - mkdir -p $HOME/results
  - pip install .
  - npm install
script:
  - for f in $(git ls-tree -r -t --full-name --name-only HEAD) ; do
      touch -d $(git log --pretty=format:%cI -1 HEAD -- "$f") "$f";
    done
  - ls -l $HOME/results
  - ls -l data/*.yml
  - python process.py --multi -v -v --limit=150 --out=$HOME/results
  - python util/combine.py --results=$HOME/results --out=client/static
  - npm run lint
  - npm run build
# https://docs.travis-ci.com/user/deployment/pages/
