sudo: false
language: python
python: pypy3.5
cache:
  - npm
  - directories:
    - $HOME/results
install:
  - mkdir -p $HOME/results
  - nvm install v10
  - node --version
  - npm --version
  - pip install -U pip
  - pip install .
  - pip freeze
  - npm prune
  - npm install
script:
  - for f in $(git ls-tree -r -t --full-name --name-only HEAD) ; do
      touch -d $(git log --pretty=format:%cI -1 HEAD -- "$f") "$f";
    done
  - ls -l $HOME/results
  - ls -l data/*.yml
  - npm run lint
  - python -u process.py --multi -v -v --limit='150,stopped.txt' --arg=time_delta=0.02 --out=$HOME/results
  - python util/combine.py --results=$HOME/results --out=client/static
  - npm run build
  - if [ ! -f stopped.txt ]; then
      export COMPLETE="true";
    fi
# https://docs.travis-ci.com/user/deployment/pages/
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: true
  local-dir: dist
  on:
    condition: $COMPLETE = "true"
    branch: master
